version: '3.1'

services:

  mongo:
    container_name: orbit-mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${MONGO_DATA_VOLUME}:/data/db

  postgres:
    container_name: orbit-postgres
    hostname: postgres
    image: postgres:14
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DATE_VOLUME}:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: postgres

  redis:
    image: redis:latest
    container_name: orbit-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_VOLUME}:/data

  elastic:
    container_name: orbit-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTIC_PORT}:9200


